/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API and PostgreSQL readiness */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse the subject taxonomy
         * @description Returns the tree. By default only nodes that pass the depth gate are included, along with the ancestors needed to reach them.
         */
        get: operations["CatalogController_getTaxonomy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/nodes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one taxonomy node */
        get: operations["CatalogController_getNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published resources with facet counts
         * @description Filtering by node includes the whole subtree beneath it. Only published resources are returned.
         */
        get: operations["CatalogController_listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/resources/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one published resource */
        get: operations["CatalogController_getResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest existing catalog resources for a learner
         * @description Deterministic ranking with per-suggestion reasons. Age-band fit gates the score; cost can only count against a resource. Gender is not accepted and cannot influence ranking.
         */
        post: operations["CatalogController_suggest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated tutor profile */
        get: operations["UsersController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TaxonomyTreeNodeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId: string | null;
            /** @enum {string} */
            scheme: "isced-f" | "uk-nc" | "sced" | "internal";
            code: string;
            slug: string;
            /** @description Dot-separated node codes from the root */
            path: string;
            depth: number;
            /** @description Localised labels keyed by language tag; "en" is required */
            names: {
                [key: string]: string;
            };
            resourceCount: number;
            mediaTypeCount: number;
            /** @description True once the node passes the depth gate */
            published: boolean;
            children: components["schemas"]["TaxonomyTreeNodeDto"][];
        };
        TaxonomyNodeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId: string | null;
            /** @enum {string} */
            scheme: "isced-f" | "uk-nc" | "sced" | "internal";
            code: string;
            slug: string;
            /** @description Dot-separated node codes from the root */
            path: string;
            depth: number;
            /** @description Localised labels keyed by language tag; "en" is required */
            names: {
                [key: string]: string;
            };
            resourceCount: number;
            mediaTypeCount: number;
            /** @description True once the node passes the depth gate */
            published: boolean;
        };
        ResourceSummaryDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            description: string | null;
            /** @enum {string} */
            mediaType: "course" | "tutorial" | "book" | "reference" | "audio" | "video";
            provider: string;
            language: string;
            /** @enum {string} */
            licence: "cc0" | "public-domain" | "cc-by" | "cc-by-sa" | "platform-tos" | "proprietary";
            /** @enum {string} */
            usageTier: "open" | "embed" | "commercial";
            /** @enum {string} */
            costModel: "free" | "freemium" | "paid";
            durationSeconds: number | null;
            pageCount: number | null;
            /** Format: date-time */
            lastVerifiedAt: string | null;
        };
        ResourceFacetsDto: {
            mediaType: {
                [key: string]: number;
            };
            costModel: {
                [key: string]: number;
            };
        };
        ResourceListDto: {
            items: components["schemas"]["ResourceSummaryDto"][];
            total: number;
            facets: components["schemas"]["ResourceFacetsDto"];
        };
        TierCapabilitiesDto: {
            deepLink: boolean;
            embed: boolean;
            mirror: boolean;
            affiliate: boolean;
        };
        ResourceDetailDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            description: string | null;
            /** @enum {string} */
            mediaType: "course" | "tutorial" | "book" | "reference" | "audio" | "video";
            provider: string;
            language: string;
            /** @enum {string} */
            licence: "cc0" | "public-domain" | "cc-by" | "cc-by-sa" | "platform-tos" | "proprietary";
            /** @enum {string} */
            usageTier: "open" | "embed" | "commercial";
            /** @enum {string} */
            costModel: "free" | "freemium" | "paid";
            durationSeconds: number | null;
            pageCount: number | null;
            /** Format: date-time */
            lastVerifiedAt: string | null;
            /** Format: uri */
            canonicalUrl: string;
            /**
             * Format: uri
             * @description Only present when the usage tier permits embedding
             */
            embedUrl: string | null;
            /**
             * Format: uri
             * @description Where the visitor should be sent: the affiliate link where the tier permits one, otherwise the canonical URL
             */
            outboundUrl: string;
            attributionText: string | null;
            authors: string[];
            isbn: string | null;
            capabilities: components["schemas"]["TierCapabilitiesDto"];
        };
        LearnerContextDto: {
            /** @description Taxonomy node slug to suggest within */
            node: string;
            /** @enum {string} */
            ageBand: "5-7" | "8-10" | "11-13" | "14-16" | "17-18";
            /**
             * @description BCP-47 language tag
             * @example en-GB
             */
            locale: string;
            /** @description Learner interests, from a closed vocabulary */
            interests?: ("animals" | "art" | "baking" | "cars" | "coding" | "dance" | "dinosaurs" | "fashion" | "football" | "gaming" | "history" | "music" | "nature" | "puzzles" | "reading" | "robotics" | "science-fiction" | "space" | "sport" | "theatre")[];
            /**
             * @default medium
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /**
             * @default step-by-step
             * @enum {string}
             */
            learningPreference: "visual" | "narrative" | "step-by-step" | "challenge-first";
            /**
             * @description Accepted for forward compatibility; not yet used in ranking
             * @default medium
             * @enum {string}
             */
            attentionSpan: "short" | "medium" | "long";
            /** @default false */
            allowPaid: boolean;
            /** @default 6 */
            limit: number;
            /**
             * @description "full" also returns the factors that contributed nothing
             * @default top
             * @enum {string}
             */
            explain: "top" | "full";
        };
        AgeGateDto: {
            /** @enum {string} */
            factor: "age-band-fit";
            /** @enum {string} */
            level: "exact" | "adjacent" | "distant" | "none";
            /** @description Multiplies the whole weighted sum */
            multiplier: number;
        };
        SuggestionReasonDto: {
            /** @enum {string} */
            factor: "topic-relevance" | "interest-overlap" | "reading-level-fit" | "confidence-fit" | "media-preference" | "quality" | "cost";
            /** @description Ordinal level for this factor, e.g. "exact" */
            level: string;
            /** @description Signed contribution to the score */
            contribution: number;
        };
        SuggestionDto: {
            resource: components["schemas"]["ResourceSummaryDto"];
            score: number;
            gate: components["schemas"]["AgeGateDto"];
            reasons: components["schemas"]["SuggestionReasonDto"][];
            /** @description Pushed down by a media-type or provider cap */
            diversityCapped: boolean;
        };
        SuggestionListDto: {
            items: components["schemas"]["SuggestionDto"][];
            weightsVersion: string;
            candidatesConsidered: number;
            /**
             * @description Why the list is empty; null when it is not
             * @enum {string|null}
             */
            emptyCause: "no-candidates-in-subtree" | "all-filtered-by-safety-vetting" | "all-filtered-by-cost" | "all-filtered-by-language" | "all-filtered-by-missing-enrichment" | "all-suppressed-by-age-gate" | null;
        };
        CurrentUserDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string | null;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            /** @description The database is unavailable */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_getTaxonomy: {
        parameters: {
            query?: {
                /** @description Include nodes that have not yet passed the depth gate */
                includeUnpublished?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyTreeNodeDto"][];
                };
            };
        };
    };
    CatalogController_getNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodeDto"];
                };
            };
            /** @description No node with that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_listResources: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                costModel?: "free" | "freemium" | "paid";
                language?: string;
                mediaType?: "course" | "tutorial" | "book" | "reference" | "audio" | "video";
                node?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceListDto"];
                };
            };
        };
    };
    CatalogController_getResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceDetailDto"];
                };
            };
            /** @description No published resource with that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_suggest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerContextDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionListDto"];
                };
            };
            /** @description The learner context is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No taxonomy node with that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserDto"];
                };
            };
            /** @description A valid Auth0 access token is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
